mysqldb:
  ip: "mariadb"
  port: 3306
  db: test
  user: root
  passwd: "root"
  auto_create_tables: True # 是否自动建表 建议当表不存在是设置为true，表存在是设置为false，加快软件启动速度

redisdb:
  ip: redis
  port: 6379
  db: 0
  passwd:

spider:
  monitor_interval: 3600 # 公众号扫描新发布文章周期时间间隔 单位秒
  ignore_haved_crawl_today_article_account: true # 忽略已经抓取到今日发布文章的公众号，即今日不再监测该公众号
  redis_task_cache_root_key: wechat # reids 中缓存任务的根key 如 wechat:
  zombie_account_not_publish_article_days: 90 # 连续90天未发布新文章，判定为僵尸账号，日后不再监控
  spider_interval:
    min_sleep_time: 5
    max_sleep_time: 10
  no_task_sleep_time: 3600 # 当无任务时休眠时间
  service_port: 8080 # 服务的端口
  # crawl_time_range: 2019-07-10 00:00:00~2019-07-01 00:00:00 # 抓取的时间范围 若不限制最近时间可写为 ~2019-07-01 00:00:00 若想抓取全部历史则不设置
  crawl_time_range:

log:
  level: INFO
  to_file: false
  log_path: ./logs/wechat_spider.log

mitm:
  log_level: 0 # mitm框架日志的打印级别。值在0~3之间，值越大，输出的日志信息越详细，默认是1。详见：https://docs.mitmproxy.org/stable/concepts-options/

wechat:
  cookie: "appmsglist_action_3907326541=card; ua_id=O5T6ChVi5qDVnWxwAAAAAI1Jh4KdtKmvb__Bsub_PYw=; mm_lang=zh_CN; _clck=3907326541|1|f6a|0; rewardsn=; wxtokenkey=777; pgv_info=ssid=s3063972355; pgv_pvid=6305076999; eas_sid=xMA7JbFZVanizs8WwLMzSr9YQi; _qpsvr_localtk=0.004155613692446769; RK=3F9wtkmMU6; ptcz=26706f3c9065bf8a18542ea03452db5d08cd661cd9adb9eac58590e6f2b08ec4; lostarkqqcomrouteLine=a20230314index_a20230314index; wwapp.vid=; wwapp.cst=; wwapp.deviceid=; appmsg_token=1211_y3yZFh67JdIH2Ll3B14QEnXTLVPCpmbKjlHbEhW0gkh9hJjIX5t8atb0V7c8E3mvohLVbWGsyEkS2CwN; lang=zh_CN; wxuin=1089095992; devicetype=Windows10; version=62060834; pass_ticket=OYykAz8tz321UO5f6ZJhCZPHBRueNujtUEDwt9L3FWb/N84ieH4J6ngoqbAcH8t2LQNxJfRMtRW20uMeETfILw==; wap_sid2=CLiSqYcEEooBeV9ISENycGxKU0xKckdtTWNLdnVIRWZBSlczSGc0Z2owWDZtQkh3UGhzUlFFMFpIMDFKWjZoTEJzV0FxYTJtejdRV0ZVVUFsYUlZR2tWdktqQnlkMkNwNGtITEJvNGtQLTdYOFRacTNYWlkwMmFUc2c5OTJuUjNlMkpuOGthWXZIeUY1b1NBQUF+MLOL2qEGOAxAlE4=; uuid=ca2d95d3533bdd98d692398a09b03404; rand_info=CAESIEQxp2byMz4oTIXEODL+izQnaPPBE/CnGIv6JP7znxtM; slave_bizuin=3907326541; data_bizuin=3907326541; bizuin=3907326541; data_ticket=mVf5k7LxBB/iW6XQUFd5VBqmLW9TYc8GLAsKf7dGMJrc8V0FzH0k74fcLmtoPaT/; slave_sid=anE3MnY2ZnpKMnZuRzU0OGVrX3hOd1pQSVFCdkI0eEI2QklBTmd0YW1YUHpnc3pFVlAxSUhzZWpDbGwyNUJ2X1Z4ZU85Y29MQnhXU2d2NnNCeUhOR3RBMTZUYXhtMDdHeE9acjVLano5eG1qbFhVU0c5enlEQWNpNnhpTDB5N1NGZGFHMXpISE5OZGI3aTJX; slave_user=gh_8f2c3072b8fa; xid=cd68db73eb8548171025d98618200932"
  token: "2038225367"
  count: 5